config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    #resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:update]
    resources :orders, only: [:index, :show, :update,]
    get 'orders' => 'orders#order_history', as: 'order_history'
  end

  scope module: :public do
    root to: "homes#top"
    get "about" =>"homes#about", as: 'about'
    resources :items, only: [:index,:show,]
    #resources :registrations, only: [:new,:create]
    #resources :sessions, only: [:new, :create, :destroy]
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :customers, only: [:edit, :update]
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/check' => 'customers#check', as: 'check'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "orders/complete" =>"orders#complete", as: 'complete'
    post "orders/confilm" =>"orders#confilm", as: 'confilm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :shipping_addresses, only:[:index, :edit, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price * quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :address, uniqueness: true

  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

validates :name, presence: true
validates :tax_out_price, presence: true
validates :explanation, presence: true
# validates :is_onsele, presence: true

  has_one_attached :profile_image

  has_many :order_items, dependent: :destroy
  #has_many :order_item_orders, through: order_items, source: order
  belongs_to :genre
  has_many :cart_items

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/cake.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (tax_out_price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

enum payment_method: { credit_card: 0, transfer: 1 }

belongs_to :customer
has_many :order_items, dependent: :destroy
#has_many :order_item_items, through: order_items, source: item
enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item
  
  
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

   def address_display
   '〒' + postcode + ' ' + address + ' ' + name
   end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id]) 
    if @customer.update(customer_params)
     flash[:notice] = "You have updated customer successfully."
     redirect_to admin_customer_path(@customer.id)  
    else
      render :edit
    end
  end


protected
 
 def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :telephone_number, :email, :is_active)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end

 protected
 
  def order_params
    params.require(:order).permit(:status, :payment_method)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admin/customers/edit.html.erb
<div class='container' >
  <div class='row'>
    <div class='col'>
      <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
      <table>
      <thead>
        <th><h2><%= @customer.last_name+@customer.first_name %>さんの会員情報編集</h2></th>
      </thead>
     <p></p>
     <p></p>

 <tbody>
   <div class="form-group">
   <tr><td>会員ID</td><td><%= @customer.id %></td></tr>
   <tr><td>氏名</td>
    <td><%= f.text_field :last_name %></td>
    <td><%= f.text_field :first_name %></td></tr>
   <tr><td>フリガナ</td></td>
    <td><%= f.text_field :last_name_kana %></td>
    <td><%= f.text_field :first_name_kana %></td></tr>
   <tr><td>郵便番号</td><td><%= f.text_field :postcode %></td></tr>
   <tr><td>住所</td><td><%= f.text_field :address %></td></tr>
   <tr><td>電話番号</td><td><%= f.text_field :telephone_number %></td></tr>
   <tr><td>メールアドレス</td><td><%= f.text_field :email %></td></tr>
   <tr><td>会員ステータ</td>
       <td>
         <%= f.radio_button :is_active, :true %>
         <%= f.label :true, "有効" %>

         <%= f.radio_button :is_active, :false %>
         <%= f.label :false, "退会" %></td></tr>
    <tr><td><%= f.submit '変更内容を保存', class: "btn btn-success" %></td></tr>

   </div>
   </tbody>
   </table>
  <% end %>
   </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container' >
  <div class='row'>
    <div class='col'>
<h2>会員一覧</h2>
  <table>
   <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
   </thead>
     <tbody>
<% @customers.each do |customer| %>
   <tr>
    <td><%= customer.id %></td>
    <td><%= link_to customer.last_name+customer.first_name, admin_customer_path(customer.id) %></td>
    <td><%= customer.email %></td>
    <td><% if customer.is_active %>
    有効
   <% else %>
   退会済み
    <% end %></td>
  </tr>
  <% end %>
  
  </tbody>
</table>
<%= paginate @customers %>
 </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container' >
  <div class='row'>
    <div class='col'>
     <table>
      <thead>
<h2><%= @customer.last_name+@customer.first_name %>さんの会員詳細</h2>
  </thead>
  <tbody>
   <tr>
     <td>会員ID</td>
     <td><%= @customer.id %></td>
   </tr>
   <tr>
     <td>氏名</td>
     <td><%= @customer.last_name+" "+@customer.first_name %></td>
   </tr>
   <tr>
     <td>フリガナ</td>
     <td><%= @customer.last_name_kana+" "+@customer.first_name_kana %></td>
   </tr>
   <tr>
     <td>郵便番号</td>
     <td><%= @customer.postcode %></td>
   </tr>
   <tr>
     <td>住所</td>
     <td><%= @customer.address %></td>
   </tr>
   <tr>
     <td>電話番号</td>
     <td><%= @customer.telephone_number %></td>
   </tr>
   <tr>
     <td>メールアドレス</td>
    <td><%= @customer.email %></td>
   </tr>
   <tr>
    <td>会員ステータス</td>
    <td><% if @customer.is_active %>
    有効
   <% else %>
   退会済み
    <% end %></td>
  </tr>
  </tbody>
</table>

<div>
<%= link_to "編集する", edit_admin_customer_path(@customer.id) %>
|
<%= '注文一覧を見る'%>
</div>
</div>
</div>
</div>

app/views/customers/check.html.erb
<h1>Customers#check</h1>
<p>Find me in app/views/customers/check.html.erb</p>

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customers/index.html.erb
<h1>Customers#index</h1>
<p>Find me in app/views/customers/index.html.erb</p>

app/views/customers/show.html.erb
<h1>Customers#show</h1>
<p>Find me in app/views/customers/show.html.erb</p>

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>