config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    #resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:update]
    resources :orders, only: [:index, :show, :update,]
    get 'orders' => 'orders#order_history', as: 'order_history'
  end

  scope module: :public do
    root to: "homes#top"
    get "about" =>"homes#about", as: 'about'
    resources :items, only: [:index,:show,]
    #resources :registrations, only: [:new,:create]
    #resources :sessions, only: [:new, :create, :destroy]
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :customers, only: [:edit, :update]
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/check' => 'customers#check', as: 'check'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "orders/complete" =>"orders#complete", as: 'complete'
    post "orders/confilm" =>"orders#confilm", as: 'confilm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :shipping_addresses, only:[:index, :edit, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price * quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :address, uniqueness: true

  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

validates :name, presence: true
validates :tax_out_price, presence: true
validates :explanation, presence: true
# validates :is_onsele, presence: true

  has_one_attached :profile_image

  has_many :order_items, dependent: :destroy
  #has_many :order_item_orders, through: order_items, source: order
  belongs_to :genre
  has_many :cart_items

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/cake.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (tax_out_price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

enum payment_method: { credit_card: 0, transfer: 1 }

belongs_to :customer
has_many :order_items, dependent: :destroy
#has_many :order_item_items, through: order_items, source: item
enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item
  
  
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

   def address_display
   '〒' + postcode + ' ' + address + ' ' + name
   end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end

 protected
 
  def order_params
    params.require(:order).permit(:status, :payment_method)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.page(params[:page])
  end
  
  def order_history
    @orders = CustomerId.Order.page(params[:page])
    @order = Order.find(params[:id])
  end
  
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id]) 
    if@order.update(order_params)
     flash[:notice] = "You have updated order successfully."
     redirect_to admin_order_path(@order.id)  
    else
     redirect_to admin_order_path(@order.id)
    end
  end

 protected
 
def order_params
    params.require(:order).permit(:status, :payment_method)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admin/orders/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center'>

    <h2>注文履歴一覧</h2>
    <table>
      <thead>
       <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
    <tbody>
     <% @orders.each do |order| %>
        <tr>
           <td><%= link_to order.created_at, admin_order_path(order.id) %></td>
           <td><%= order.customer.last_name+order.customer.first_name %></td>
           <td><%= order.order_items.quantity %></td>
           <td><%= Order.statuses_i18n[order.status] %></td>
        </tr>
    </tbody>
     <%= paginate post_images %>
   <% end %>
    </table>
   </div>
  </div>
</div>

app/views/admin/orders/order_history.html.erb
<h2><%= @order.customer.last_name+@order.customer.first_name %>さんの注文履歴一覧</h2>
  <table>
   <thead>
    <tr>
      <th>購入日時</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
   </thead>
     <tbody>
<% @orders.each do |order| %>
   <tr>
    <td><%= link_to order.created_at, admin_order_path(order.id) %></td>
    <td><%= order.order_items.quantity %></td>
    <td><%= Order.statuses_i18n[order.status] %></td>
  </tr>
  </tbody>
  <%= paginate post_images %>
<% end %>
</table>

app/views/admin/orders/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col'>
     <h2>注文履歴詳細</h2>
     <table>
      <tr>
        <td>購入者</td>
        <td><%= @order.customer.last_name+@order.customer.first_name %></td>
      </tr>
      <tr>
        <td>注文日</td>
        <td><%= @order.created_at %></td>
      </tr>
      <tr>
        <td>配送先</td>
        <td></td><%= @order.created_at %></td>
      </tr>
      <tr>
        <td>支払い方法</td>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>
        <td>注文ステータス</td>
        <td><%= form_with model: @order, url: admin_order_path(@order.id) do |form| %>
            <%= form.select :status, [['入金待ち', 0], ['入金確認', 1], ['製作中', 2], ['発送準備中', 3], ['発送済み', 4]], { include_blank: true, selected: 0 } %>
        </td>
        <td>
        <%= form.submit '更新', class: "btn btn-success" %>
        </td>
        <% end %>
       </tr>
     </table>
   </div>
 </div><br><br>
  <div class='row'>
    <div class='col-sm'>
  <table>
   <thead>
    <tr>
      <th>商品名</th>
      <th>単価</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
      <th colspan="1"></th>
    </tr>
   </thead>
     <tbody>
<% @order_items.each do |order_item| %>
   <tr>
    <td><%= order_item.item.name %></td>
    <td><%= order_item.purchase_price %></td>
    <td><%= order_item.quantity %></td>
    <td><%= order_item.quantity*order_item.purchase_price %></td>
    <td><%= form_with model: order_item, url: admin_order_item_path(order_item.id) do |f| %>
        <%= f.select :item_status, [['着手不可', 0], ['製作待ち', 1],['製作中', 2],['製作完了', 3]], { include_blank: true, selected: 0 } %>
    </td>
    <td><%= f.submit '更新', class: "btn btn-success" %></td>
        <% end %>
   </tr>
<% end %>
  </tbody>
</table>
</div>
  </div>
</div>